/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  OrganizationApi,
  ProjectApi,
  ResourceApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { NasaTechPortCustom } from "./client-custom";

export class NasaTechPort extends NasaTechPortCustom {
  readonly organization: OrganizationApi;
  readonly project: ProjectApi;
  readonly resource: ResourceApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.organization = new OrganizationApi(configuration);
    this.project = new ProjectApi(configuration);
    this.resource = new ResourceApi(configuration);
  }

}
