/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LkuCode } from './lku-code';

/**
 * Represents a specific library item.
 * @export
 * @interface LibraryItem
 */
export interface LibraryItem {
    /**
     * Title of the library item
     * @type {string}
     * @memberof LibraryItem
     */
    'title'?: string;
    /**
     * Description of the library item.
     * @type {string}
     * @memberof LibraryItem
     */
    'description'?: string;
    /**
     * Unique identifier for the library item.
     * @type {number}
     * @memberof LibraryItem
     */
    'id'?: number;
    /**
     * 
     * @type {LkuCode}
     * @memberof LibraryItem
     */
    'contentType'?: LkuCode;
    /**
     * List of files associated with the library item.
     * @type {Array<any>}
     * @memberof LibraryItem
     */
    'files'?: Array<any>;
    /**
     * External URL for the library item.
     * @type {string}
     * @memberof LibraryItem
     */
    'url'?: string;
    /**
     * Date the library item was published.
     * @type {string}
     * @memberof LibraryItem
     */
    'publishedDateString'?: string;
    /**
     * Publisher of the library item.
     * @type {string}
     * @memberof LibraryItem
     */
    'publishedBy'?: string;
}

