/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Lookup code type further showing how the lookup codes within this type will be used.
 * @export
 * @interface LkuCodeType
 */
export interface LkuCodeType {
    /**
     * Description of the LKU Code Type
     * @type {string}
     * @memberof LkuCodeType
     */
    'description'?: string;
    /**
     * Unique ID for this LKU Code Type
     * @type {number}
     * @memberof LkuCodeType
     */
    'lkuCodeTypeId'?: number;
    /**
     * Unique text code type that represents this LKU Code
     * @type {string}
     * @memberof LkuCodeType
     */
    'codeType'?: string;
}

