/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LkuCodeType } from './lku-code-type';

/**
 * Lookup code representing more data about an object usually stored in our database.
 * @export
 * @interface LkuCode
 */
export interface LkuCode {
    /**
     * Description of the LKU Code
     * @type {string}
     * @memberof LkuCode
     */
    'description'?: string;
    /**
     * Unique ID for this LKU Code
     * @type {number}
     * @memberof LkuCode
     */
    'lkuCodeId'?: number;
    /**
     * Unique text code that represents this LKU Code
     * @type {string}
     * @memberof LkuCode
     */
    'code'?: string;
    /**
     * Unique ID for the LKU Code Type
     * @type {number}
     * @memberof LkuCode
     */
    'lkuCodeTypeId'?: number;
    /**
     * 
     * @type {LkuCodeType}
     * @memberof LkuCode
     */
    'lkuCodeType'?: LkuCodeType;
    /**
     * Display order
     * @type {number}
     * @memberof LkuCode
     */
    'displayOrder'?: number;
}

