/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LkuCode } from './lku-code';

/**
 * Represents a physical location.
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * Unique ID for this location
     * @type {number}
     * @memberof Location
     */
    'locationId'?: number;
    /**
     * First line of address for location
     * @type {string}
     * @memberof Location
     */
    'addressLine1'?: string;
    /**
     * Second line of address for location
     * @type {string}
     * @memberof Location
     */
    'addressLine2'?: string;
    /**
     * City for location
     * @type {string}
     * @memberof Location
     */
    'city'?: string;
    /**
     * 
     * @type {LkuCode}
     * @memberof Location
     */
    'locationType'?: LkuCode;
    /**
     * Unique ID for the lookup code representing the location type
     * @type {number}
     * @memberof Location
     */
    'locationTypeId'?: number;
    /**
     * State for location
     * @type {string}
     * @memberof Location
     */
    'state'?: string;
    /**
     * State Territory name for location
     * @type {string}
     * @memberof Location
     */
    'stateTerritoryName'?: string;
    /**
     * ZIP code for location
     * @type {string}
     * @memberof Location
     */
    'zip'?: string;
    /**
     * Secondary ZIP code for location
     * @type {string}
     * @memberof Location
     */
    'zip2'?: string;
    /**
     * True if this location is located in North America
     * @type {string}
     * @memberof Location
     */
    'NALocation'?: string;
    /**
     * 
     * @type {LkuCode}
     * @memberof Location
     */
    'country'?: LkuCode;
    /**
     * Unique ID for the lookup code representing the location country
     * @type {number}
     * @memberof Location
     */
    'countryId'?: number;
    /**
     * A string representing the full location
     * @type {string}
     * @memberof Location
     */
    'shortLocationString'?: string;
}

