/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represents a file associated with a library item.
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * Unique identifier for the file.
     * @type {number}
     * @memberof ModelFile
     */
    'fileId'?: number;
    /**
     * The TechPort URL at which the file is accessible for download.
     * @type {string}
     * @memberof ModelFile
     */
    'url'?: string;
    /**
     * The size of the file in bytes.
     * @type {number}
     * @memberof ModelFile
     */
    'fileSize'?: number;
    /**
     * The file extension for the file.
     * @type {string}
     * @memberof ModelFile
     */
    'fileExtension'?: string;
    /**
     * The file name.
     * @type {string}
     * @memberof ModelFile
     */
    'fileName'?: string;
}

