/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Organization } from './organization';

/**
 * 
 * @export
 * @interface OrganizationGetInformationResponse
 */
export interface OrganizationGetInformationResponse {
    /**
     * 
     * @type {Organization}
     * @memberof OrganizationGetInformationResponse
     */
    'organization'?: Organization;
}

