/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrganizationType } from './organization-type';

/**
 * 
 * @export
 * @interface OrganizationListTypesResponse
 */
export interface OrganizationListTypesResponse {
    /**
     * 
     * @type {Array<OrganizationType>}
     * @memberof OrganizationListTypesResponse
     */
    'organizations'?: Array<OrganizationType>;
}

