/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LkuCode } from './lku-code';
import { Location } from './location';

/**
 * A NASA center/facility associated with an project
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * Unique ID for this organization
     * @type {number}
     * @memberof Organization
     */
    'organizationId'?: number;
    /**
     * The acronym of the organization
     * @type {string}
     * @memberof Organization
     */
    'acronym'?: string;
    /**
     * Fax number of the organization
     * @type {string}
     * @memberof Organization
     */
    'fax'?: string;
    /**
     * True if the organization is an active organization
     * @type {boolean}
     * @memberof Organization
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Location}
     * @memberof Organization
     */
    'location'?: Location;
    /**
     * Unique ID representing the organizations location
     * @type {number}
     * @memberof Organization
     */
    'locationId'?: number;
    /**
     * The name of the organization
     * @type {string}
     * @memberof Organization
     */
    'organizationName'?: string;
    /**
     * 
     * @type {LkuCode}
     * @memberof Organization
     */
    'organizationType'?: LkuCode;
    /**
     * Unique ID for the lookup code representing the organization type
     * @type {number}
     * @memberof Organization
     */
    'organizationTypeId'?: number;
    /**
     * Unique ID for the parent organization
     * @type {number}
     * @memberof Organization
     */
    'parentOrganizationId'?: number;
    /**
     * The phone number for the organization
     * @type {string}
     * @memberof Organization
     */
    'phone'?: string;
    /**
     * Unique ID for the replacement organization
     * @type {number}
     * @memberof Organization
     */
    'replacementOrganizationId'?: number;
    /**
     * The URL for the organization
     * @type {string}
     * @memberof Organization
     */
    'url'?: string;
    /**
     * True if the organization is in North America
     * @type {boolean}
     * @memberof Organization
     */
    'NAOrganization'?: boolean;
    /**
     * True if the organization is external to NASA
     * @type {boolean}
     * @memberof Organization
     */
    'external'?: boolean;
    /**
     * Amount of links this organization has
     * @type {number}
     * @memberof Organization
     */
    'linkCount'?: number;
    /**
     * Unique identifier assigned to U.S. academic institutions by MUREP.
     * @type {number}
     * @memberof Organization
     */
    'murepUnitId'?: number;
    /**
     * The employer identification number (EIN) of the entity.
     * @type {string}
     * @memberof Organization
     */
    'ein'?: string;
    /**
     * The unique entity identifier (UEI) of the entity.
     * @type {string}
     * @memberof Organization
     */
    'uei'?: string;
    /**
     * The DUNS number assigned to the organization.
     * @type {string}
     * @memberof Organization
     */
    'dunsNumber'?: string;
    /**
     * A key/value pair of strings describing the organization MSI status by fiscal year.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Organization
     */
    'msiData'?: { [key: string]: Array<string>; };
    /**
     * The organization set-aside types.
     * @type {Array<string>}
     * @memberof Organization
     */
    'setAsideData'?: Array<string>;
}

