/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Organization } from './organization';

/**
 * Represents a NASA program.
 * @export
 * @interface Program
 */
export interface Program {
    /**
     * Title for the program
     * @type {string}
     * @memberof Program
     */
    'title'?: string;
    /**
     * Description for the program
     * @type {string}
     * @memberof Program
     */
    'description'?: string;
    /**
     * Unique ID for this program
     * @type {number}
     * @memberof Program
     */
    'programId'?: number;
    /**
     * Acronym for this program
     * @type {string}
     * @memberof Program
     */
    'acronym'?: string;
    /**
     * True if the program is still active
     * @type {boolean}
     * @memberof Program
     */
    'active'?: boolean;
    /**
     * 
     * @type {Program}
     * @memberof Program
     */
    'parentProgram'?: Program;
    /**
     * Unique ID for the parent program
     * @type {number}
     * @memberof Program
     */
    'parentProgramId'?: number;
    /**
     * 
     * @type {Organization}
     * @memberof Program
     */
    'responsibleMd'?: Organization;
    /**
     * Unique ID for the parent responsible mission directorate
     * @type {number}
     * @memberof Program
     */
    'responsibleMdId'?: number;
}

