/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectListAvailableIdsResponse
 */
export interface ProjectListAvailableIdsResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectListAvailableIdsResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectListAvailableIdsResponse
     */
    'lastUpdated'?: string;
}

