/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectFindMatchingProjectsResponseInner
 */
export interface ProjectFindMatchingProjectsResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ProjectFindMatchingProjectsResponseInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectFindMatchingProjectsResponseInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectFindMatchingProjectsResponseInner
     */
    'id'?: number;
}

