/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Represents data associated with a single taxonomy node entity.
 * @export
 * @interface TaxonomyNode
 */
export interface TaxonomyNode {
    /**
     * Title of the taxonomy node
     * @type {string}
     * @memberof TaxonomyNode
     */
    'title'?: string;
    /**
     * Unique identifier for the taxonomy node
     * @type {number}
     * @memberof TaxonomyNode
     */
    'taxonomyNodeId'?: number;
    /**
     * Unique identifier for the root of this taxonomy node
     * @type {number}
     * @memberof TaxonomyNode
     */
    'taxonomyRootId'?: number;
    /**
     * Unique identifier for the taxonomy node/root that is the direct parent of this taxonomy node
     * @type {number}
     * @memberof TaxonomyNode
     */
    'parentNodeId'?: number;
    /**
     * The level of this node on the tree (0 being the root)
     * @type {number}
     * @memberof TaxonomyNode
     */
    'level'?: number;
    /**
     * Code of the taxonomy node
     * @type {string}
     * @memberof TaxonomyNode
     */
    'code'?: string;
    /**
     * Definition of the taxonomy node
     * @type {string}
     * @memberof TaxonomyNode
     */
    'definition'?: string;
    /**
     * Defines whether this node has children
     * @type {boolean}
     * @memberof TaxonomyNode
     */
    'hasChildren'?: boolean;
    /**
     * Published URL of the taxonomy node
     * @type {string}
     * @memberof TaxonomyNode
     */
    'publishedUrl'?: string;
}

