/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Technology Area for a given technology that corresponds to the NASA Technology Roadmap.
 * @export
 * @interface TechnologyArea
 */
export interface TechnologyArea {
    /**
     * The title of the Technology Area.
     * @type {string}
     * @memberof TechnologyArea
     */
    'title'?: string;
    /**
     * Unique identifier for the Technology Area.
     * @type {number}
     * @memberof TechnologyArea
     */
    'id'?: number;
    /**
     * The code identifier for the Technology Area.
     * @type {string}
     * @memberof TechnologyArea
     */
    'code'?: string;
}

