/*
TechPort

TechPort RESTful API

The version of the OpenAPI document: 3.13.2
Contact: hq-techport@mail.nasa.gov

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TaxonomyNode } from './taxonomy-node';

/**
 * Represents a taxonomy node in a tree.
 * @export
 * @interface TreeNode
 */
export interface TreeNode {
    /**
     * 
     * @type {TaxonomyNode}
     * @memberof TreeNode
     */
    'content'?: TaxonomyNode;
    /**
     * 
     * @type {Array<TreeNode>}
     * @memberof TreeNode
     */
    'children'?: Array<TreeNode>;
}

